apiVersion: v1
kind: Pod
metadata:
  name: chida.test.com
  labels:
    app: firstapp
spec:
  containers:
  - name: firstapp
    image: tomcat
    ports:
    - name: siteport
      containerPort: 8080
