apiVersion: v1
kind: ReplicationController
metadata:
  name: chida-test-Controller
spec:
  replicas: 2
  selector:
    app: replica1
  template:
    metadata:
      labels:
        app: replica1
    spec:
     containers:
     - name: firstapp
       image: tomcat
       ports:
       - name: siteport
         containerPort: 8080